#! /bin/sh

# TODO(move this to a bash script that checks wheter devices are plugged in or not)
xrandr --output HDMI-0 --primary --auto --output DP-1 --auto --left-of HDMI-0

nitrogen --restore &
picom &

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 4 5 6
bspc monitor DP-1 -d 1 2 3

bspc config border_width         4
bspc config window_gap			 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config ignore_ewmh_focus    true

bspc config focused_border_color '#ffa600'
bspc config active_border_color  '#003f5c'
# bspc config normal_border_color  '#58508d'

bspc rule -a firefox:Navigator desktop=^1 follow=on focus=on
bspc rule -a Alacritty:Alacritty desktop=^4 follow=on focus=on
bspc rule -a discord:discord desktop=^6 focus=off follow=off 
bspc rule -a 'VirtualBox Manager':'VirtualBox Manager' desktop=^5 focus=off follow=off 
