#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift -l '41.652779:-4.723611' &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#ffa600'
bspc config active_border_color  '#003f5c'

bspc rule -a firefoxdeveloperedition:Navigator desktop=^1 follow=on focus=on
bspc rule -a Alacritty:Alacritty desktop=^2 follow=on focus=on
bspc rule -a discord:discord desktop=^3 focus=off follow=off 
